version: '3.8'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: customer_db
    volumes:
      - my_mongo_data:/data/db
    ports:
      - "27017:27017"

  fastapi-app:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "80:8000"
    environment:
      MONGO_DETAILS: "mongodb://user:password@mongo:27017"

volumes:
  my_mongo_data:
